name: Build with devkitPPC

on:
  release:
    types: [published]
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:
  build-stable:
    name: Stable Build
    runs-on: ubuntu-latest
    container:
      image: docker://devkitpro/devkitppc:20220103
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
       
      - name: Build Wii and GC executables
        run: |
          make
          mkdir apps
          mv HBC apps/Wii-donut
          mv Wii-donut.c.dol apps/Wii-donut/boot.dol
          zip -9 -r wii_release.zip apps/
          make clean
          make -f Makefile.gc

      - name: Upload result
        uses: actions/upload-artifact@v2.3.1
        with:
          name: Stable build results
          path: |
            wii_release.zip
            Wii-donut.c-gc.dol
  build-unstable:
    name: Canary Build
    runs-on: ubuntu-latest
    container:
      image: docker://devkitpro/devkitppc:latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
       
      - name: Build Wii and GC executables
        run: |
          make
          make clean
          make -f Makefile.gc
